In [1]:
import numpy as np

In [2]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print X


[[ -0.16016247   3.97247831 -19.04036352 ..., -15.79545227   2.52166284
    5.23382858]
 [ 17.10478399  15.87875009 -13.44899792 ...,  -1.92168737   8.97622068
    1.32175055]
 [-17.92731037 -17.12893664 -14.58546335 ...,  19.68714199  -1.45501053
   10.5195035 ]
 ..., 
 [ 20.49714611  14.22497665   3.12449152 ..., -10.10722991 -10.06045517
   -0.32581488]
 [ -3.5092209   -3.75002189  -0.70210986 ...,   2.01962843  -2.41227437
   12.20711118]
 [  8.34973905  -0.40528144  -9.18163452 ...,   8.69123846 -10.72365733
    4.08188828]]


In [4]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print X_norm

[[ 0.32264764 -2.87350092  1.2602273  ..., -0.54422693 -0.48207419
   2.13094163]
 [ 0.63512489  0.67659418  1.08952753 ..., -0.56387355  0.45107432
  -0.20647778]
 [ 0.93464686  0.03229312  0.53013914 ...,  1.13581853 -0.17630005
   1.10588907]
 ..., 
 [-0.91998349 -0.42948111 -0.45892035 ...,  0.1879117   1.50657369
   0.29676852]
 [ 2.32560978 -1.28251428 -0.2453745  ...,  0.51596595 -0.49087114
  -0.60338147]
 [-0.17011165  1.76743988  0.65495935 ..., -0.0869333   0.61544193
  -1.60496677]]


In [41]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

r = np.sum(Z, axis=1)
print np.nonzero(r > 10)

(array([1, 4, 5]),)


In [46]:
#generate identity matrix 3*3 and merge them into 6*3
A = np.eye(3)
B = np.eye(3)
print A
print B

C = np.hstack((A, B))
print C

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  1.]]
